substitutions:
  name: "gatekeeper-xiao-1"
  wifi_ssid: "GADI_IoT"
  wifi_pass: "01012010"
  mqtt_broker: "172.16.10.12"

esphome:
  name: "${name}"

esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: arduino

wifi:
  ssid: "${wifi_ssid}"
  password: "${wifi_pass}"
  fast_connect: true

mqtt:
  id: mqtt_client
  broker: "${mqtt_broker}"
  username: "gatekeeper_pi" # Optional
  password: "gatekeeper_pi" # Optional

logger:

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true
  on_ble_advertise:
    then:
      - lambda: |-
          // Topic: gatekeeper/satellite/<satellite_id>/<identifier>
          // We use the node name as satellite ID
          
          char topic[256];
          char payload[128];
          
          // Check if this is an iBeacon advertisement
          if (x.get_ibeacon().has_value()) {
            // iBeacon detected - publish by UUID
            auto beacon = x.get_ibeacon().value();
            std::string uuid_str = beacon.get_uuid().to_string();
            
            // Topic: gatekeeper/satellite/{name}/uuid/{UUID}
            sprintf(topic, "gatekeeper/satellite/${name}/uuid/%s", uuid_str.c_str());
            
            // Payload: JSON with rssi, major, minor
            sprintf(payload, "{\"rssi\": %d, \"major\": %d, \"minor\": %d}", 
                    x.get_rssi(), beacon.get_major(), beacon.get_minor());
          } else {
            // Non-iBeacon - publish by MAC (legacy/fallback)
            sprintf(topic, "gatekeeper/satellite/${name}/%s", x.address_str().c_str());
            sprintf(payload, "%d", x.get_rssi());
          }
          
          // Publish to MQTT
          id(mqtt_client).publish(topic, payload);

